module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/J12ww3y4hmeEOGfhk4nYT6?mode=ems_copy_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.postimg.cc/QCvFcGXY/86701-F52-1-E26-4335-9-AF0-E48-C580337-EC.jpg',
    NEWSLETTER_JID: '120363400431057294@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝚃𝙾𝙶𝙴-𝙼𝙳 𝚅𝟻 𝙼𝙸𝙽𝙸 𝙱𝙾𝚃',
    OWNER_NAME: '𝚃𝙾𝙶𝙴 𝙸𝙽𝚄𝙼𝙰𝙺𝙸',
    OWNER_NUMBER: '24102178283',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '𝚃𝙾𝙶𝙴-𝙼𝙳 𝚅𝟻 𝙼𝙸𝙽𝙸 𝙱𝙾𝚃',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb5T8ccIN9ir9iDb8O33',
};
